/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResultIndexImport } from './routes/result/index'

// Create Virtual Routes

const ErrorLazyImport = createFileRoute('/error')()
const StartIndexLazyImport = createFileRoute('/start/')()
const QuestionnaireIndexLazyImport = createFileRoute('/questionnaire/')()
const QuestionnaireIdIndexLazyImport = createFileRoute('/questionnaire/$id/')()
const QuestionnaireIdEditIndexLazyImport = createFileRoute(
  '/questionnaire/$id/edit/',
)()

// Create/Update Routes

const ErrorLazyRoute = ErrorLazyImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/error.lazy').then((d) => d.Route))

const StartIndexLazyRoute = StartIndexLazyImport.update({
  id: '/start/',
  path: '/start/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/start/index.lazy').then((d) => d.Route))

const QuestionnaireIndexLazyRoute = QuestionnaireIndexLazyImport.update({
  id: '/questionnaire/',
  path: '/questionnaire/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/questionnaire/index.lazy').then((d) => d.Route),
)

const ResultIndexRoute = ResultIndexImport.update({
  id: '/result/',
  path: '/result/',
  getParentRoute: () => rootRoute,
} as any)

const QuestionnaireIdIndexLazyRoute = QuestionnaireIdIndexLazyImport.update({
  id: '/questionnaire/$id/',
  path: '/questionnaire/$id/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/questionnaire/$id/index.lazy').then((d) => d.Route),
)

const QuestionnaireIdEditIndexLazyRoute =
  QuestionnaireIdEditIndexLazyImport.update({
    id: '/questionnaire/$id/edit/',
    path: '/questionnaire/$id/edit/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/questionnaire/$id/edit/index.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorLazyImport
      parentRoute: typeof rootRoute
    }
    '/result/': {
      id: '/result/'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultIndexImport
      parentRoute: typeof rootRoute
    }
    '/questionnaire/': {
      id: '/questionnaire/'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/start/': {
      id: '/start/'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/questionnaire/$id/': {
      id: '/questionnaire/$id/'
      path: '/questionnaire/$id'
      fullPath: '/questionnaire/$id'
      preLoaderRoute: typeof QuestionnaireIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/questionnaire/$id/edit/': {
      id: '/questionnaire/$id/edit/'
      path: '/questionnaire/$id/edit'
      fullPath: '/questionnaire/$id/edit'
      preLoaderRoute: typeof QuestionnaireIdEditIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/error': typeof ErrorLazyRoute
  '/result': typeof ResultIndexRoute
  '/questionnaire': typeof QuestionnaireIndexLazyRoute
  '/start': typeof StartIndexLazyRoute
  '/questionnaire/$id': typeof QuestionnaireIdIndexLazyRoute
  '/questionnaire/$id/edit': typeof QuestionnaireIdEditIndexLazyRoute
}

export interface FileRoutesByTo {
  '/error': typeof ErrorLazyRoute
  '/result': typeof ResultIndexRoute
  '/questionnaire': typeof QuestionnaireIndexLazyRoute
  '/start': typeof StartIndexLazyRoute
  '/questionnaire/$id': typeof QuestionnaireIdIndexLazyRoute
  '/questionnaire/$id/edit': typeof QuestionnaireIdEditIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/error': typeof ErrorLazyRoute
  '/result/': typeof ResultIndexRoute
  '/questionnaire/': typeof QuestionnaireIndexLazyRoute
  '/start/': typeof StartIndexLazyRoute
  '/questionnaire/$id/': typeof QuestionnaireIdIndexLazyRoute
  '/questionnaire/$id/edit/': typeof QuestionnaireIdEditIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/error'
    | '/result'
    | '/questionnaire'
    | '/start'
    | '/questionnaire/$id'
    | '/questionnaire/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/error'
    | '/result'
    | '/questionnaire'
    | '/start'
    | '/questionnaire/$id'
    | '/questionnaire/$id/edit'
  id:
    | '__root__'
    | '/error'
    | '/result/'
    | '/questionnaire/'
    | '/start/'
    | '/questionnaire/$id/'
    | '/questionnaire/$id/edit/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ErrorLazyRoute: typeof ErrorLazyRoute
  ResultIndexRoute: typeof ResultIndexRoute
  QuestionnaireIndexLazyRoute: typeof QuestionnaireIndexLazyRoute
  StartIndexLazyRoute: typeof StartIndexLazyRoute
  QuestionnaireIdIndexLazyRoute: typeof QuestionnaireIdIndexLazyRoute
  QuestionnaireIdEditIndexLazyRoute: typeof QuestionnaireIdEditIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  ErrorLazyRoute: ErrorLazyRoute,
  ResultIndexRoute: ResultIndexRoute,
  QuestionnaireIndexLazyRoute: QuestionnaireIndexLazyRoute,
  StartIndexLazyRoute: StartIndexLazyRoute,
  QuestionnaireIdIndexLazyRoute: QuestionnaireIdIndexLazyRoute,
  QuestionnaireIdEditIndexLazyRoute: QuestionnaireIdEditIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/error",
        "/result/",
        "/questionnaire/",
        "/start/",
        "/questionnaire/$id/",
        "/questionnaire/$id/edit/"
      ]
    },
    "/error": {
      "filePath": "error.lazy.tsx"
    },
    "/result/": {
      "filePath": "result/index.tsx"
    },
    "/questionnaire/": {
      "filePath": "questionnaire/index.lazy.tsx"
    },
    "/start/": {
      "filePath": "start/index.lazy.tsx"
    },
    "/questionnaire/$id/": {
      "filePath": "questionnaire/$id/index.lazy.tsx"
    },
    "/questionnaire/$id/edit/": {
      "filePath": "questionnaire/$id/edit/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
