/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const StartLazyImport = createFileRoute('/start')()
const ResultLazyImport = createFileRoute('/result')()
const QuestionnaireLazyImport = createFileRoute('/questionnaire')()

// Create/Update Routes

const StartLazyRoute = StartLazyImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/start.lazy').then((d) => d.Route))

const ResultLazyRoute = ResultLazyImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/result.lazy').then((d) => d.Route))

const QuestionnaireLazyRoute = QuestionnaireLazyImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/questionnaire.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/questionnaire': {
      id: '/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireLazyImport
      parentRoute: typeof rootRoute
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultLazyImport
      parentRoute: typeof rootRoute
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/questionnaire': typeof QuestionnaireLazyRoute
  '/result': typeof ResultLazyRoute
  '/start': typeof StartLazyRoute
}

export interface FileRoutesByTo {
  '/questionnaire': typeof QuestionnaireLazyRoute
  '/result': typeof ResultLazyRoute
  '/start': typeof StartLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/questionnaire': typeof QuestionnaireLazyRoute
  '/result': typeof ResultLazyRoute
  '/start': typeof StartLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/questionnaire' | '/result' | '/start'
  fileRoutesByTo: FileRoutesByTo
  to: '/questionnaire' | '/result' | '/start'
  id: '__root__' | '/questionnaire' | '/result' | '/start'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  QuestionnaireLazyRoute: typeof QuestionnaireLazyRoute
  ResultLazyRoute: typeof ResultLazyRoute
  StartLazyRoute: typeof StartLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  QuestionnaireLazyRoute: QuestionnaireLazyRoute,
  ResultLazyRoute: ResultLazyRoute,
  StartLazyRoute: StartLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/questionnaire",
        "/result",
        "/start"
      ]
    },
    "/questionnaire": {
      "filePath": "questionnaire.lazy.tsx"
    },
    "/result": {
      "filePath": "result.lazy.tsx"
    },
    "/start": {
      "filePath": "start.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
